---
version: "2"

services:
  our-app:
    build:
    environment:
      - MODE=dev
      - ELASTICSEARCH_HOST=127.0.0.1
      - ELASTICSEARCH_PORT=8200
    volumes:
      - .:/code
    depends_on:
      - elasticsearch
      - rabbitmq
    ports:
      - "8080:8080"

    elasticsearch:
      image: elasticsearch:5-alpine
      restart: unless-stopped
      command: elasticsearch -Etransport.host=127.0.0.1
      environment:
        - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      ports:
        - "8200:8200"
        - "8300:8300"
      volumes:
        - ../data:/usr/share/elasticsearch/data

    rabbitmq:
      image: rabbitmq:3.6.1-management
      environment:
        - RABBITMQ_DEFAULT_USER=admin
        - RABBITMQ_DEFAULT_PASS=admin
      ports:
        - "8023:15672"
        - "8024:5672"